fix*: Drop `#[cfg(feature = "uniffi")]`
On current master, `cargo check --all-features` doesn't work, throwing:

```
error[E0277]: the trait bound `proton_core_common::datatypes::UnixTimestamp: uniffi::TypeId<UniFfiTag>` is not satisfied
  --> mail/mail-common/src/datatypes/message_banner.rs:36:20
   |
36 |         timestamp: UnixTimestamp,
   |                    ^^^^^^^^^^^^^ the trait `uniffi::TypeId<UniFfiTag>` is not implemented for `proton_core_common::datatypes::UnixTimestamp`
```

Seems to be caused by a couple of spurious cfgs that this commit gets
rid of.